apiVersion: helm.sdk.operatorframework.io/v1
kind: Nginx
metadata:
  name: nginx-sample
  annotations:
    helm.operator-sdk/upgrade-force: "true"
    helm.operator-sdk/install-disable-hooks: "true"
    helm.operator-sdk/upgrade-disable-hooks: "true"
    helm.operator-sdk/uninstall-disable-hooks: "true"
spec:
  replicaCount: 1
  image:
    nginx:
      repository: nginx
      tag: "7.0"
  
  service:
    name: http
    type: LoadBalancer
    externalPort: 80
    internalPort: 8080
  
  hostPort: 8009
