linters:
  disable-all: true
  enable:
    - deadcode
    # requires fixes
    # - dupl
    - errcheck
    - gocyclo
    # requires fixes
    # - gofmt
    - goimports
    - golint
    # requires fixes
    # gosec
    - gosimple
    - govet
    - ineffassign
    # requires fixes
    # - interfacer
    # - lll
    - maligned
    - misspell
    - nakedret
    - prealloc
    # requires fixes
    # - scopelint
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - goconst
run:
  deadline: 5m
