name: CI

on:
  push: {}
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Cache go module cache
      id: cache-go-mod
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: make build

    - name: Test
      run: make test

    - uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: cover.out

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29

  deploy:
    name: Deploy
    needs:
    - test
    - lint
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Prepare
      id: prep
      run: |
        TAG=ci
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          TAG=${GITHUB_REF#refs/tags/}
        elif [[ $GITHUB_REF == refs/heads/* ]]; then
          TAG=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
        elif [[ $GITHUB_REF == refs/pull/* ]]; then
          TAG=pr-${{ github.event.number }}
        fi

        echo ::set-output name=tag::${TAG}
        echo ::set-output name=platforms::linux/amd64,linux/arm64,linux/ppc64le,linux/s390x

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Quay
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
        registry: quay.io

    - name: Build helm-operator image
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: ${{ steps.prep.outputs.platforms }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: quay.io/joelanford/helm-operator:${{ steps.prep.outputs.tag }}

    - name: Build example nginx-operator image
      uses: docker/build-push-action@v2
      with:
        context: ./example
        platforms: ${{ steps.prep.outputs.platforms }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: quay.io/joelanford/nginx-operator:${{ steps.prep.outputs.tag }}
